//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 29.11.2012 18:59:22
namespace Lex.Db.WebEntities
{
    
    /// <summary>
    /// There are no comments for SampleDbContext in the schema.
    /// </summary>
    public partial class SampleDbContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SampleDbContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SampleDbContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SampleDbModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Lex.Db.WebEntities", typeName.Substring(13)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Lex.Db.WebEntities", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SampleDbModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Person> _People;
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Companies
        {
            get
            {
                if ((this._Companies == null))
                {
                    this._Companies = base.CreateQuery<Company>("Companies");
                }
                return this._Companies;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Companies;
        /// <summary>
        /// There are no comments for DeletedItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DeletedItem> DeletedItems
        {
            get
            {
                if ((this._DeletedItems == null))
                {
                    this._DeletedItems = base.CreateQuery<DeletedItem>("DeletedItems");
                }
                return this._DeletedItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DeletedItem> _DeletedItems;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
        /// <summary>
        /// There are no comments for DeletedItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDeletedItems(DeletedItem deletedItem)
        {
            base.AddObject("DeletedItems", deletedItem);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString(ModelEdmx);
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelEdmx = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"SampleDbModel\" xmlns=\"http://schemas.microsoft.com/ado/2008/09/edm\"><" +
                "EntityType Name=\"Person\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=" +
                "\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Ts\" " +
                "Type=\"Edm.DateTime\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" /><Property Name=\"F" +
                "irstName\" Type=\"Edm.String\" MaxLength=\"100\" Unicode=\"true\" /><Property Name=\"Las" +
                "tName\" Type=\"Edm.String\" MaxLength=\"100\" Unicode=\"true\" /><Property Name=\"Compan" +
                "yId\" Type=\"Edm.Int32\" /><NavigationProperty Name=\"Company\" Relationship=\"SampleD" +
                "bModel.CompanyPerson\" ToRole=\"Company\" FromRole=\"Person\" /></EntityType><EntityT" +
                "ype Name=\"Company\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=" +
                "\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http:" +
                "//schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Ts\" Type=\"" +
                "Edm.DateTime\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Name\" T" +
                "ype=\"Edm.String\" MaxLength=\"100\" Unicode=\"true\" /><NavigationProperty Name=\"Peop" +
                "le\" Relationship=\"SampleDbModel.CompanyPerson\" ToRole=\"Person\" FromRole=\"Company" +
                "\" /></EntityType><EntityType Name=\"DeletedItem\"><Key><PropertyRef Name=\"Id\" /><P" +
                "ropertyRef Name=\"EntitySet\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullabl" +
                "e=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft" +
                ".com/ado/2009/02/edm/annotation\" /><Property Name=\"EntitySet\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"150\" /><Property Name=\"Ts\" Type=\"Edm.DateTime\" Nulla" +
                "ble=\"false\" ConcurrencyMode=\"Fixed\" /></EntityType><Association Name=\"CompanyPer" +
                "son\"><End Type=\"SampleDbModel.Company\" Role=\"Company\" Multiplicity=\"0..1\" /><End" +
                " Type=\"SampleDbModel.Person\" Role=\"Person\" Multiplicity=\"*\" /><ReferentialConstr" +
                "aint><Principal Role=\"Company\"><PropertyRef Name=\"Id\" /></Principal><Dependent R" +
                "ole=\"Person\"><PropertyRef Name=\"CompanyId\" /></Dependent></ReferentialConstraint" +
                "></Association></Schema><Schema Namespace=\"Lex.Db.Server\" xmlns=\"http://schemas." +
                "microsoft.com/ado/2008/09/edm\"><EntityContainer Name=\"SampleDbContext\" m:IsDefau" +
                "ltEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.m" +
                "icrosoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"People\" EntityType=\"Sa" +
                "mpleDbModel.Person\" /><EntitySet Name=\"Companies\" EntityType=\"SampleDbModel.Comp" +
                "any\" /><EntitySet Name=\"DeletedItems\" EntityType=\"SampleDbModel.DeletedItem\" /><" +
                "AssociationSet Name=\"CompanyPerson\" Association=\"SampleDbModel.CompanyPerson\"><E" +
                "nd Role=\"Person\" EntitySet=\"People\" /><End Role=\"Company\" EntitySet=\"Companies\" " +
                "/></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString(string edmxToParse)
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for SampleDbModel.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("People")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Person : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="ts">Initial value of Ts.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Person CreatePerson(int ID, global::System.DateTime ts)
        {
            Person person = new Person();
            person.Id = ID;
            person.Ts = ts;
            return person;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Ts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Ts
        {
            get
            {
                return this._Ts;
            }
            set
            {
                this.OnTsChanging(value);
                this._Ts = value;
                this.OnTsChanged();
                this.OnPropertyChanged("Ts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Ts;
        partial void OnTsChanging(global::System.DateTime value);
        partial void OnTsChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CompanyId;
        partial void OnCompanyIdChanging(global::System.Nullable<int> value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
                this.OnPropertyChanged("Company");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SampleDbModel.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Companies")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Company : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="ts">Initial value of Ts.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(int ID, global::System.DateTime ts)
        {
            Company company = new Company();
            company.Id = ID;
            company.Ts = ts;
            return company;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Ts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Ts
        {
            get
            {
                return this._Ts;
            }
            set
            {
                this.OnTsChanging(value);
                this._Ts = value;
                this.OnTsChanged();
                this.OnPropertyChanged("Ts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Ts;
        partial void OnTsChanging(global::System.DateTime value);
        partial void OnTsChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Person> People
        {
            get
            {
                return this._People;
            }
            set
            {
                this._People = value;
                this.OnPropertyChanged("People");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Person> _People = new global::System.Data.Services.Client.DataServiceCollection<Person>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SampleDbModel.DeletedItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// EntitySet
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DeletedItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id", "EntitySet")]
    public partial class DeletedItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DeletedItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="entitySet">Initial value of EntitySet.</param>
        /// <param name="ts">Initial value of Ts.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DeletedItem CreateDeletedItem(int ID, string entitySet, global::System.DateTime ts)
        {
            DeletedItem deletedItem = new DeletedItem();
            deletedItem.Id = ID;
            deletedItem.EntitySet = entitySet;
            deletedItem.Ts = ts;
            return deletedItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property EntitySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EntitySet
        {
            get
            {
                return this._EntitySet;
            }
            set
            {
                this.OnEntitySetChanging(value);
                this._EntitySet = value;
                this.OnEntitySetChanged();
                this.OnPropertyChanged("EntitySet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EntitySet;
        partial void OnEntitySetChanging(string value);
        partial void OnEntitySetChanged();
        /// <summary>
        /// There are no comments for Property Ts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Ts
        {
            get
            {
                return this._Ts;
            }
            set
            {
                this.OnTsChanging(value);
                this._Ts = value;
                this.OnTsChanged();
                this.OnPropertyChanged("Ts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Ts;
        partial void OnTsChanging(global::System.DateTime value);
        partial void OnTsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
